#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier check failed. Run `yarn format`, add changes and try commit again.';
    false;
)

# Check ESLint standards
npm run check-lint ||
(
        echo 'ESLint check failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Check tsconfig failes. Make the changes required above.'
    false;
)

echo 'Committing...'
